server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/sbRegistrionApp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
    
login-app:
   message:
     invalidCredentials: Your Credentials are Invalid
     accloacked: Your Account Locked
     
    